# -*- coding: utf-8 -*-
"""Evaluacion Semana 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_Ub9vZgBrONj1o-fyR72ogihux9CLd3

1. Crear una función para el cálculo del promedio de temperatura

  ● Define una función llamada calcular_promedio_temperatura que
  tome una lista de temperaturas como argumento y devuelva el
  promedio de las temperaturas.

  ● Llame a la función con los datos proporcionados y muestra el
  resultado.
"""

#creacion de la funcion con los datos proporcinados como argumento
def calcular_promedio_temperatura(temperaturas):
  #regresar 0 en caso de que temperaturas sea falsy, como 0 o vacia
  if not temperaturas:
    return 0

  #calculo de la suma, largo con funciones sum()y len() y promedio
  suma_temperaturas = sum(temperaturas)
  cantidad_de_temperaturas = len(temperaturas)
  promedio_temperaturas = suma_temperaturas/cantidad_de_temperaturas
  return promedio_temperaturas

  #lista de datos proporcionados
temperaturas = [22.5, 23.0, 21.8, 22.3, 22.9, 23.1, 22.8]

  #llamada y asignacion de la funcion
promedio = calcular_promedio_temperatura(temperaturas)
print(f"El promedio es: {promedio:.2f}°C ")

"""---

2. Automatizar la identificación de temperaturas fuera de rango

● Define una función llamada temperaturas_fuera_de_rango que tome
una lista de temperaturas y dos valores que representen los límites
inferior y superior del rango aceptable. La función debe devolver una
lista de temperaturas que estén fuera del rango especificado.

● Llame a la función con los datos proporcionados y un rango de 22.0 a
 23.0 grados Celsius. Muestra las temperaturas que están fuera de este
rango
"""

#creacion de la funcion con los argumentos temperatura y ambos limites
def temperaturas_fuera_de_rango(temperaturas, limite_inferior, limite_superior):

    #comprension de la lista, primero la nueva expresion, luego los elementos en el iterable (temp in temperaturas), mas los condicionales relevantes y asignacion
    #el acance nos permite usar la lista temperaturas
    fuera_de_rango = [temp for temp in temperaturas if temp < limite_inferior or temp > limite_superior]
    return fuera_de_rango

#limites(hardcoded en este caso)
limite_inferior = 22.0
limite_superior = 23.0

#llamada y asignacion
temps_fuera_de_rango = temperaturas_fuera_de_rango(temperaturas, limite_inferior, limite_superior)

#formato
print(f"Las temperaturas fuera del rango son:")
print(* temps_fuera_de_rango, sep=", ")

"""---

3. Crear una función para generar un informe simple

  ● Define una función llamada generar_informe_temperaturas que tome
  una lista de temperaturas y genere un informe que incluya el número
  total de mediciones, el promedio de temperatura, la temperatura
  máxima y la temperatura mínima.
  
  ● Llame a la función con los datos proporcionados y muestre el informe
"""

#creacion de funcion
def generar_informe_temperatures(temperaturas):
  #asignaciones (google colab mantiene un mismo alcance, permitiendonos usar la lista temperaturas )
  total_mediciones=len(temperaturas)
  promedio_temperaturas=calcular_promedio_temperatura(temperaturas)
  #uso de funciones max y min para conseguir los items mas pequenos y/o grandes
  temperatura_maxima=max(temperaturas)
  temperatura_minima=min(temperaturas)

  #string multilinea, contiene 5 f-strings para imprimir variables en los curly braces
  informe=(
      f"Informe de Temperaturas:\n"
      f" Mediciones totales: {total_mediciones}\n"
      #.2f=2 decimales
      f" Promedio de temperatura: {promedio:.2f}°C\n"
      f" Temperatura maxima: {temperatura_maxima:.2f}°C\n"
      f" Temperatura minima: {temperatura_minima} °C"
  )
  return informe
#asignacion e impresion
informe2=generar_informe_temperatures(temperaturas)
print(informe2)